version: '3.8'

services:
  frontend:
    container_name: cod3s-project-${PROJECT_NAME}-webapp
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${NGINX_PORT}:80"
      - "${NGINX_SSL_PORT}:443"
    environment:
      - NODE_ENV=production
      - BACKEND_PORT=${BACKEND_PORT}
      - NGINX_SSL_PORT=${NGINX_SSL_PORT}
    networks:
      - default_network
    volumes:
      - ./certs:/etc/nginx/ssl

networks:
  default_network:
    name: ${PROJECT_NAME}_network
    driver: bridge
    external: true
