version: '3.8'

services:
  frontend:
    container_name: cod3s-project-${PROJECT_NAME}-webapp
    build:
      context: .
      dockerfile: Dockerfile  # Utilise le Dockerfile pour Vite
    volumes:
      - .:/app  # Monter le répertoire de travail pour un développement interactif
      - /app/node_modules  # Volumes pour éviter la réinstallation des dépendances à chaque modification
    ports:
      - "3000:3000"  # Mapper le port 3000 du conteneur au port 3000 de l'hôte
    environment:
      - NODE_ENV=development
    networks:
      - cod3s_network

  nginx:
    container_name: cod3s-project-${PROJECT_NAME}-nginx
    build: 
      context: .
      dockerfile: Dockerfile.nginx  # Dockerfile pour Nginx uniquement
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Utilise la configuration Nginx personnalisée
      - ./certs:/etc/nginx/ssl  # Monter les certificats SSL générés
    ports:
      - "80:80"  # Mapper le port 80 du conteneur au port 80 de l'hôte
      - "443:443"  # Mapper le port 443 pour HTTPS
    depends_on:
      - frontend  # Assure-toi que le service frontend est démarré en premier
    networks:
      - cod3s_network

networks:
  cod3s_network:
   
